/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limelight_emulator_av_encoder_ffmpegEncoderX11 */

#ifndef _Included_com_limelight_emulator_av_encoder_ffmpegEncoderX11
#define _Included_com_limelight_emulator_av_encoder_ffmpegEncoderX11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limelight_emulator_av_encoder_ffmpegEncoderX11
 * Method:    startStream
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_limelight_emulator_av_encoder_ffmpegEncoderX11_startStream
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_limelight_emulator_av_encoder_ffmpegEncoderX11
 * Method:    requestIdrFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limelight_emulator_av_encoder_ffmpegEncoderX11_requestIdrFrame
  (JNIEnv *, jobject);


void streamBytes(uint8_t *data, int size);

#ifdef __cplusplus
}
#endif
#endif
